name: Build CIA

# Controls when the workflow will run
on:
 push:
   branches:
     - 3ds-main
 pull_request:
   branches:
     - 3ds-main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup DKP and Mania repository
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=$DEVKITPRO/devkitARM
          rm Game
          cd ..
          git clone https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation
          ln -s $(pwd)/RSDKv5-Decompilation/ Sonic-Mania-Decompilation/dependencies/v5_3DS
          ln -s $(pwd)/Sonic-Mania-Decompilation/SonicMania RSDKv5-Decompilation/Game

      - name: Build ELF and 3DSX
        run: |
          cd ../Sonic-Mania-Decompilation
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/3DS.cmake -DGAME_STATIC=ON -DRSDK_PATH="dependencies/v5_3DS" -DRETRO_DISABLE_PLUS=ON
          make -j$(nproc)
          echo Build done.

      - name: Package CIA
        run: |
          export ELF_PATH=$(pwd)/../Sonic-Mania-Decompilation/build/dependencies/v5_3DS/RSDKv5U.elf
          cd 3ds
          ./build_cia.sh $ELF_PATH

      # Setup artifact folder
      - name: Setup artifact folder
        run: |
          mkdir artifacts
          cp ../Sonic-Mania-Decompilation/build/dependencies/v5_3DS/RetroEngine.3dsx artifacts/SonicMania.3dsx
          cp 3ds/out/SonicMania.cia artifacts/


      # Publish Artifacts
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sonicmania
          path: artifacts
